# -*- coding: utf-8 -*-
"""inflectionReduction.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Rt8ltmHlXcmbdePreKTxBqazDl2iQvmC
"""

#from util import *

# Add your import statements here
import nltk
nltk.download('wordnet')
nltk.download('omw-1.4')
from nltk.stem import WordNetLemmatizer
from nltk.stem import PorterStemmer

class InflectionReduction:

    def reduce(self, text):
        """
        Stemming/Lemmatization

        Parameters
        ----------
        arg1 : list
            A list of lists where each sub-list a sequence of tokens
            representing a sentence

        Returns
        -------
        list
            A list of lists where each sub-list is a sequence of
            stemmed/lemmatized tokens representing a sentence
        """

        reducedText = []
        wnl = WordNetLemmatizer()
        for i in range(0,len(text)):
          arr=[]
          curr=text[i]
          for j in range(0,len(curr)):
            s=wnl.lemmatize(curr[j])
            arr.append(s)
          reducedText.append(arr)
        '''
        reducedText = []
        ps = PorterStemmer()
        for i in range(0,len(text)):
          arr=[]
          curr=text[i]
          for j in range(0,len(curr)):
            s=ps.stem(curr[j])
            arr.append(s)
          reducedText.append(arr)
          '''

          

        #Fill in code here
        
        return reducedText

#lemmatization done